### PR TITLE
Aware broker tests

### PR DESCRIPTION
**Pull request by ahelmbr**
Added the aware broker tests functionality to this type of tests. 
Added also the hivemq-sparkplug-aware-extension.zip to be able to run the tests.

### CODE REVIEW

**Review by icraggs-sparkplug — CHANGES_REQUESTED** [review]
Could you remove the changes to PayloadTest.java from this PR please? That one is one I've been working on and is changed in the other open PR. It's better to keep a PR focused.

**Review by icraggs-sparkplug — COMMENTED** [review]
Actually the changes to PayloadTest.java are not in an open PR - those changes have been merged already.

**Comment by ahelmbr** [comment]
I reverted the changes on PayloadTest.java

**Comment by icraggs-sparkplug** [comment]
Thanks Anja.  Unfortunately there are still some changes in PayloadTest.java showing, causing some conflicts.

**Comment by icraggs-sparkplug** [comment]
I merged and resolved the remaining conflict.

**Pull request merged**
