### PR TITLE
TCK implementation proposal

### PR DESCRIPTION
**Pull request by icraggs-sparkplug**
I've put together an example of how a TCK test could work.  This one is for the primary host session establishment.  This isn't meant necessarily to be merged as-is, but as a starting point for discussion.  It includes a Python test program to illustrate how it would work.  

To run it, the built sparkplug-tck jar should be put into the HiveMQ extension directory before starting HiveMQ, then the python program run against it.  You should see all the tests pass.

### CODE REVIEW

**Review by wes-johnson — APPROVED** [review]

**Comment by icraggs-sparkplug** [comment]
What should I do to allow this PR to be merged?  I expect the Python test program or something like it, ought to go into Tahu - certainly removed from here.  Is there anything else?

**Comment by icraggs-sparkplug** [comment]
Oh, copyright headers.

**Comment by wes-johnson** [comment]
I think moving the test application to Tahu should be all that is needed. I think it can be merged after that. If you make a PR over there, I can merge it.

**Comment by icraggs-sparkplug** [comment]
Ok, I added some more placeholder test classes, and removed the Python test program.

**Pull request merged**
