### PR TITLE
Edge session establishment

### PR DESCRIPTION
**Pull request by mbmcpartland**

### CODE REVIEW

**Review by icraggs-sparkplug — COMMENTED** [review]
This is looking good.  It needs to be merged with the latest changes from develop.

However, most of the assertions in this test don't exist in the spec.  I get the report below.  The number of assertions in the section 5.2, operational behavior section for edge session establishment, is only 2 (not covered here).  Are you expecting some more assertions to be added by @wes-johnson ?  

We should also add the relevant assertions from the payloads sections of the spec: 6.4.19 NBIRTH, 6.4.26 NDEATH, and some from 6.4.5.

<p style="color: rgb(0, 0, 0); font-family: verdana, arial, sans-serif; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The following 17 tests do not match any known assertions:</p>

Section | Assertion | Test Class | Test Method
-- | -- | -- | --
operational_behavior_edge_node_session_establishment | edge-subscribe-ncmd | org.eclipse.sparkplug.tck.test.edgeSessionEstablishment | check_subscribe_topics()
operational_behavior_edge_node_session_establishment | edge-subscribe-dcmd | org.eclipse.sparkplug.tck.test.edgeSessionEstablishment | check_subscribe_topics()
operational_behavior_edge_node_session_establishment | edge-subscribe-state | org.eclipse.sparkplug.tck.test.edgeSessionEstablishment | check_subscribe_topics()
operational_behavior_edge_node_session_establishment | edge-death-qos | org.eclipse.sparkplug.tck.test.edgeSessionEstablishment | checkWillMessage()
operational_behavior_edge_node_session_establishment | edge-death-seq | org.eclipse.sparkplug.tck.test.edgeSessionEstablishment | checkWillMessage()
operational_behavior_edge_node_session_establishment | edge-death-retain | org.eclipse.sparkplug.tck.test.edgeSessionEstablishment | checkWillMessage()
operational_behavior_edge_node_session_establishment | edge-death-bdseq | org.eclipse.sparkplug.tck.test.edgeSessionEstablishment | checkWillMessage()
operational_behavior_edge_node_session_establishment | edge-death-cert | org.eclipse.sparkplug.tck.test.edgeSessionEstablishment | connect()
operational_behavior_edge_node_session_establishment | edge-birth-bdseq | org.eclipse.sparkplug.tck.test.edgeSessionEstablishment | publish()
operational_behavior_edge_node_session_establishment | edge-birth-qos | org.eclipse.sparkplug.tck.test.edgeSessionEstablishment | publish()
operational_behavior_edge_node_session_establishment | edge-birth-retain | org.eclipse.sparkplug.tck.test.edgeSessionEstablishment | publish()
operational_behavior_edge_node_session_establishment | edge-birth-seq | org.eclipse.sparkplug.tck.test.edgeSessionEstablishment | publish()
operational_behavior_edge_node_session_establishment | edge-birth-timestamp | org.eclipse.sparkplug.tck.test.edgeSessionEstablishment | publish()
operational_behavior_edge_node_session_establishment | edge-rebirth | org.eclipse.sparkplug.tck.test.edgeSessionEstablishment | publish()
operational_behavior_edge_node_session_establishment | edge-bdseq | org.eclipse.sparkplug.tck.test.edgeSessionEstablishment | publish()
operational_behavior_edge_node_session_establishment | edge-birth-metrics | org.eclipse.sparkplug.tck.test.edgeSessionEstablishment | publish()
operational_behavior_edge_node_session_establishment | edge-state-before-birth | org.eclipse.sparkplug.tck.test.edgeSessionEstablishment | publish()

**Comment by mbmcpartland** [comment]
Most of the tests in edge session establishment now match known assertions

**Review by icraggs-sparkplug — APPROVED** [review]
The test is looking good.  When I run it using Ignition, I get the following test results:

topics-dbirth-timestamp: PASS;
topics-dbirth-mqtt: PASS;
topics-nbirth-timestamp: PASS;
payloads-dbirth-timestamp: PASS;
edge-subscribe-dcmd: ;
message-flow-edge-node-birth-publish-subscribe: FAIL (Edge node must subscribe to state before publishing NBIRTH);
payloads-nbirth-bdseq: PASS;
payloads-nbirth-rebirth: PASS;
payloads-dbirth-qos: PASS;
payloads-dbirth-seq: PASS;
payloads-sequence-num-zero-nbirth: PASS;
topics-nbirth-bdseq-included: PASS;
topics-dbirth-seq: PASS;
payloads-dbirth-order: ;
payloads-nbirth-retain: PASS;
topics-ndeath-seq: PASS;
payloads-ndeath-seq: PASS;
payloads-ndeath-bdseq: PASS;
payloads-nbirth-qos: PASS;
topics-nbirth-mqtt: PASS;
topics-nbirth-seq-num: PASS;
payloads-ndeath-will-message: FAIL (NDEATH not registered as Will in connect packet);
payloads-nbirth-seq: PASS;
edge-subscribe-ncmd: ;
payloads-dbirth-seq-inc: PASS;
topics-nbirth-rebirth-metric: PASS;
topics-ndeath-payload: PASS;
payloads-ndeath-will-message-qos: PASS;
payloads-ndeath-will-message-retain: PASS;
topics-nbirth-bdseq-matching: PASS;
payloads-dbirth-retain: PASS;
OVERALL: FAIL;

Looking through the incoming messages, it looks like the test is correct according to the spec, and that Ignition isn't (like subscribing to the STATE topic).  

Is this what's expected from Ignition at the moment?

**Comment by icraggs-sparkplug** [comment]
Mitchell and I are having a discussion about the behavior of Ignition with this test.  But I'd like to get this merged as it's a good basis and the test itself is working.

**Pull request merged**
